apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-player-info-client-pipeline
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: local
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-idp-qa/developer-charts
    targetRevision: HEAD
    path: quarkus-pipeline
    helm:
      values: |
        domain: contract-first-idp-qa
        system: local
        component: player-info-client
        deployment: jvm
  destination:
    server: https://kubernetes.default.svc
    namespace: local-build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m