apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-player-stats-prod
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: local
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-idp-qa/developer-charts
    targetRevision: HEAD
    path: quarkus-application
    helm:
      values: |
        system: local
        component: player-stats
        environment: prod
        image:
          tag: latest
        replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: local-prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m