apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-sleeper-client-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    system: local
spec:
  project: default
  source:
    repoURL: https://github.com/contract-first-idp-qa/developer-charts
    targetRevision: HEAD
    path: quarkus-application
    helm:
      values: |
        system: local
        component: sleeper-client
        environment: dev
        image:
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: local-dev
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m